//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimyRoster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoster
    {
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<decimal> SalaryCost { get; set; }
    
        public virtual Sites Sites { get; set; }
        public virtual Staffs Staffs { get; set; }
    }
}
